config/routes.rb
Rails.application.routes.draw do
  
  root "top#index"
  get "/login" => "users#login_form"
  post "/login" => "users#login"
  get "logout" => "users#logout"
  
  resources :users
  resources :posts do
    resource :likes, only: [:create, :destroy]
  end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  # belongs_to :user
  
end

app/models/post.rb
class Post < ApplicationRecord
  validates :youtube_url, presence: true, length: { minimum: 11 }
  validates :text, presence: true, length: { maximum: 140 }
  belongs_to :user
  has_many :likes
  
  def liked_by?(user)
    likes.where(user_id: user.id).exists?
  end
end

app/models/user.rb
class User < ApplicationRecord
    validates :name, presence: true, length: { maximum: 50 }
    validates :email,presence: true, length: { maximum: 50 },uniqueness: true
    validates :password, presence: true, length: {minimum: 6 }
    has_secure_password
    has_many :posts, dependent: :destroy
    # has_many :likes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :current_user

  def current_user
    @current_user = User.find_by(id: session[:id])
  end
  
  def authenticate_user
    if @current_user == nil
      flash[:alert] = "ログインが必要です"
      redirect_to '/login'
    end
  end
  
  def forbid_login_user
    if @current_user
      flash[:notice] = "ログインしています"
      redirect_to "/posts"
    end
  end

  
  def ensure_correct_user
    if @current_user.id != params[:id].to_i
      flash[:alert] = "権限がありません"
      redirect_to "/posts"
    end
  end
    
    
  
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :post_params
  
  def create
    like = Like.new(post_id: params[:post_id], user_id: @current_user.id)
    like.save
  end
  
  def destroy
    like = Like.find_by(post_id: params[:post_id], user_id: @current_user.id)
    like.destroy
  end
  
  private
    def post_params
      @post = Post.find(params[:post_id])
    end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user
  before_action :ensure_correct_user_post, only: [:edit, :update]
  
  def index
    @posts = Post.all.order(created_at: :desc).page(params[:page]).per(10)
  end
  
  def show
    @post = Post.find(params[:id])
    @user = User.find_by(id: @post.user_id)
  end
  
  def new
    @post = Post.new
  end
  
  def create
    @post = Post.new(post_params)
    @post.user_id = @current_user.id
    @post.youtube_url = params[:post][:youtube_url].last(11) 
    if @post.save
      flash[:notice] = "投稿しました"
      redirect_to posts_path
    else
      flash.now[:alert] = "URLとコメントを正しく入力してください"
      render new_post_path
    end
  end
  
  def edit
    @post = Post.find(params[:id])
  end
  
  def update
    @post = Post.find(params[:id])
    @post.update(post_params)
    if @post.save
      flash[:notice] = "投稿を編集しました"
      redirect_to posts_path
    else
      flash.now[:alert] = "URLとコメントを正しく入力してください"
      render edit_post_path
    end
  end
  
  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    flash[:alert] = "投稿を削除しました"
    redirect_to posts_path
  end
  
  def ensure_correct_user_post
    @post = Post.find(params[:id])
    if @current_user.id != @post.user_id
      flash[:alert] = "権限がありません"
      redirect_to posts_path
    end
  end
    
  
  
  private
    def post_params
      params.require(:post).permit(:text,:user_id)
    end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user, only: [:index,:show,:edit]
  before_action :ensure_correct_user, only: [:edit, :update]
  before_action :forbid_login_user, only: [:login_form, :new]
  
  def index
    @users = User.all.order(created_at: :desc)
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      session[:id] = @user.id
      redirect_to posts_path
    else
      flash.now[:alert] = "Name,Email,Passwordのいずれかが正しくありません"
      render 'new'
    end
  end
  
  def show
    @user = User.find(params[:id])
    @posts = @user.posts.order(created_at: :desc).page(params[:page]).per(10)
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to users_path
    else
      flash.now[:alert] = "Name,Emailのいずれかが正しくありません"
      render :edit
    end
  end
  
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end
  
  def login_form
  end
  
  def login
    @user = User.find_by(email: params[:email], password: params[:password])
    if @user
      session[:id] = @user.id
      redirect_to posts_path
    else
      @email = params[:email]
      @password = params[:password]
      flash.now[:alert] = "Email,Passwordのいずれかが正しくありません"
      render "login_form"
    end
  end
  
  def logout
    session[:id] = nil
    redirect_to login_path
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_flash.html.erb
<div class="flash-container">
  <% if flash.any? %>
    <div class="alert"><%= flash[:alert] %></div>
    <div class="notice"><%= flash[:notice] %></div>
  <% end %>
  </div>

app/views/layouts/_header.html.erb
<header>
  <div class="navbar">
    <% if @current_user %>
      <i class="fas fa-bars fa-lg"></i>
      <div class="sp-navbar">
        <i class="fas fa-times fa-lg"></i>
        <%= link_to @current_user.name, user_path(@current_user), class: "nav" %>
        <%= link_to "ユーザー一覧", users_path, class: "nav"%>
        <%= link_to "新規投稿", new_post_path, class: "nav" %>
        <%= link_to "投稿一覧", posts_path, class: "nav" %>
        <%= link_to "ログアウト", logout_path, class: "nav" %>
      </div>
    <% else %>
      <div class="navbar2">
        <%= link_to "Musicolor", root_path, class: "nav2 nav-home" %>
        <%= link_to "ログイン", login_path, class: "nav2" %>
        <%= link_to "アカウント作成", new_user_path, class: "nav2" %>
      </div>
    <% end %>
  </div>
  
</header>

<script>
  
  $('.fa-bars,.fa-times').on('click', function(){
    $('.sp-navbar').toggleClass('open-nav');
    $('.navbar').toggleClass('black');
    $('.fa-bars').toggleClass('lg');
  });
  
  
  
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Musicolor</title>
    <meta name="viewport" content="width=device-width,initial-scale=1.0,minimum-scale=1.0,user-scalable=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    
    <script src="https://kit.fontawesome.com/53d883e4e5.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
        <%= render 'layouts/header' %>
        <%= render 'layouts/flash' %>
        <%= yield %>
  </body>
</html>

app/views/likes/_like.html.erb
<% if post.liked_by?(@current_user) %>
  <div class="like">
    <%= link_to "いいね済み ",post_likes_path(post.id), method: 'delete', remote: true, class: "liked" %><%= post.likes.count %>
  </div>
<% else %>
  <div class="like">
    <%= link_to "いいね ", post_likes_path(post.id), method: 'post', remote: true %><%= post.likes.count %>
  </div>
<% end %>

app/views/likes/create.js.erb
$(".like-<%= @post.id %>").html("<%= j(render partial: 'like', locals:{ post: @post}) %>");

app/views/likes/destroy.js.erb
$('.like-<%= @post.id %>').html('<%= j(render partial: 'like', locals:{ post: @post}) %>');

app/views/posts/edit.html.erb
<div class="background-92vh">
  <div class="container">
    <div class="new-post">
      <%= form_with model: @post do |f| %>
      
        <div class="new-youtube">
          <div class="new-youtube-label">
            <%= f.label :youtube_url,"YouTubeのURL" %> <span class="label">※11文字以上で入力してください</span>
          </div>
          <div class="new-youtube-input">
            <%= f.text_field :youtube_url %>
          </div>
        </div>
      
        <div class="new-post-text">
          <div class="new-post-text-label">
            <%= f.label :text, "コメント" %> <span class="label">※1~140字で入力してください</span>
          </div>
          <div class="new-post-input">
            <%= f.text_area :text %>
          </div>
        </div>
        
        <%= f.submit "編集",class: "btn submit" %>
      
      <% end %>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<div class="container">
  <div class="posts">
    <%= paginate @posts %>
    <% @posts.each do |post| %>
    <div class="post">
      <div class="a-post">
        <div class="post-right">
          <div class="post-user-name">
            <%= link_to post.user.name, user_path(post.user) %>
          </div>
          <div class="post-text">
            <% if post.text.length > 15 %>
              <%= link_to "#{post.text.first(15)} ...",  post_path(post.id) %>
            <% else %>
              <%= link_to post.text,  post_path(post.id) %>
            <% end %>
          </div>
          <div class="like-<%= post.id %> post-like">
            <%= render partial: 'likes/like', locals: { post: post } %>
          </div> 
        </div>
        
        <div class="post-left">
          <div class="youtube_url">
            <iframe src="https://www.youtube.com/embed/<%= post.youtube_url %>" class="youtube"></iframe>
          </div>
        </div>
      </div>
    </div>
    <% end %>
  </div>
  <%= paginate @posts %>
</div>

app/views/posts/new.html.erb
<div class="container">
  <div class="new-post">
    <%= form_with model: @post do |f| %>

      <div class="new-youtube">
        <div class="new-youtube-label">
          <%= f.label :youtube_url,"YouTubeのURL" %> <span class="label">※11文字以上で入力してください</span>
        </div>
        <div class="new-youtube-input">
          <%= f.text_field :youtube_url %>
        </div>
      </div>
    
      <div class="new-post-text">
        <div class="new-post-text-label">
          <%= f.label :text, "コメント" %> <span class="label">※1~140字で入力してください</span>
        </div>
        <div class="new-post-input">
          <%= f.text_area :text %>
        </div>
      </div>
      
      <%= f.submit "投稿", class: "btn submit" %>
    
    <% end %>
  </div>
</div>

app/views/posts/show.html.erb
<div class="background-92vh">    
    <div class="container">
        <div class="show-post">
            <div class="show-post-right">
                <div class="show-post-user-name">
                    <%= link_to @user.name, user_path(@user) %>
                </div>
                
                <div class="show-post-text">
                    <%= @post.text %>
                </div>
            
                <div class="like-<%= @post.id %> post-like show-post-like">
                  <%= render partial: 'likes/like', locals: { post: @post } %>
                </div>
                <% if @current_user.id == @post.user_id %>
                    <%= link_to "編集",edit_post_path(@post.id), class: "btn edit" %>
                    <%= link_to "削除",post_path(@post.id), method: 'delete', class: "btn destroy" %>
                <% end %> 
            </div>
            
            <div class="post-left">
                <div class="show-youtube-url">
                    <iframe src="https://www.youtube.com/embed/<%= @post.youtube_url %>" class="show-youtube"></iframe>
                </div>
            </div>
        </div>
    </div>
</div>
    
    
    

app/views/top/index.html.erb
<div class="container">
    <h1 class="top-h1">Musicolor</h1>
    <div class="top-txt">あなたの音楽をあなたの色で</div>
</div>

app/views/users/edit.html.erb
<div class="background-92vh">
  <div class="container">
    <div class="new-post">
      <%= form_with model: @user do |f| %>
        
        <div class="new-youtube">
          <div class="new-youtube-label">
            <%= f.label :name %>
          </div>
          <div class="new-youtube-input">
            <%= f.text_field :name %>
          </div>
        </div>
        
        
        <div class="new-youtube">
          <div class="new-youtube-label">
            <%= f.label :email %>　<span class="label">※変更なしでの更新はできません。</span>
          </div>
          <div class="new-youtube-input">
            <%= f.email_field :email %>
          </div>
        </div>
        
        <%= f.submit "更新", class: "btn submit" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="users">
    <% @users.each do |user| %>
      <div class="user">
        <%= link_to user.name, "/users/#{user.id}", class: "user-name" %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/login_form.html.erb
<div class="container">
  <div class="login">
    <%= form_with url: { action: :login } do |f| %>
      
      <div class="new-youtube">
        <div class="new-youtube-label">
          <%= f.label :email %>
        </div>
        <div class="new-youtube-input">
          <%= f.email_field :email %>
        </div>
      </div>
      
      
      
      
      <div class="new-youtube">
        <div class="new-youtube-label">
          <%= f.label :password_confirmation %>
        </div>
        <div class="new-youtube-input">
          <%= f.password_field :password_confirmation %>
        </div>
      </div>
      
      <%= f.submit "ログイン", class: "btn submit" %>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<div class="container">
  <div class="new-post">
    <%= form_with model: @user do |f| %>
      
      <div class="new-user">
        <div class="new-youtube-label">
          <%= f.label :name %>
        </div>
        <div class="new-youtube-input">
          <%= f.text_field :name %>
        </div>
      </div>
      
      
      <div class="new-user">
        <div class="new-youtube-label">
          <%= f.label :email %>　<span class="label">※登録済みのEmailは使用できません。</span>
        </div>
        <div class="new-youtube-input">
          <%= f.email_field :email %>
        </div>
      </div>

      
      <div class="new-user">
        <div class="new-youtube-label">
          <%= f.label :password %>　<span class="label">※6字以上で入力してください。</span>
        </div>
        <div class="new-youtube-input">
          <%= f.password_field :password %>
        </div>
      </div>
     
      
      
      <%= f.submit "アカウント作成", class: "btn submit" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="show-user">
    <div class="show-user-name">
      <%= @user.name %>
    </div>
    
    <div class="user-show-btn">
      <% if @current_user.id == @user.id %>
        <%= link_to "編集",edit_user_path(@user.id), class: "btn edit user-edit" %>
        <%= link_to "削除",user_path(@user.id), method: 'delete', class: "btn destroy user-destroy" %>
      <% end %>
    </div>
  </div>
    
    
  <div class="posts">
    <%= paginate @posts %>
      <% @posts.each do |post| %>
        <div class="post">
          <div class="a-post">
            <div class="user-right">
              <div class="user-text">
                <% if post.text.length > 15 %>
                  <%= link_to "#{post.text.first(15)} ...",  post_path(post.id) %>
                <% else %>
                  <%= link_to post.text, post_path(post.id) %>
                <% end %>
              </div>
              <div class="like-<%= post.id %> post-like user-like">
                <%= render partial: 'likes/like', locals: { post: post } %>
              </div> 
            </div>
        
           <div class="post-left">
             <div class="youtube-url user-youtube">
              <iframe src="https://www.youtube.com/embed/<%= post.youtube_url %>" class="youtube"></iframe>
             </div>
           </div>
          </div>
        </div>
      <% end %>
    <%= paginate @posts %>
  </div>
  
</div>